<div>
    <img src="/template/images/bg21-2.jpg" alt="<?=$this->evento->titulo?>" style="width: 100%">
</div>
<div class="container pt20 pb60">
    <style>
    .video-container {
        position: relative;
        padding-bottom: 56.25%;
        padding-top: 30px; height: 0; overflow: hidden;
        }

        .video-container iframe,
        .video-container object,
        .video-container embed {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }
    </style>
    <div class="row">
        <div class="col-sm-12">
            <div class="video-container">
                <!-- <iframe src="https://drive.google.com/file/d/1Xia_CzsTdAiFhSFDUq-InicRSAp4lBH1/preview" width="640" height="360"></iframe> -->
                <iframe src="https://drive.google.com/file/d/14wSUQT9Qa9aOsppMkHg8oAX8JVRka-mm/preview" width="640" height="360"></iframe>
            </div>
            <br>
            <?=$this->partial("formacao/tti-btn.phtml", $this)?>
        </div>
    </div>
    <div class="row mb20">
        <div class="col-md-6">
            <p><a class="btn btn-sm btn-warning btn-block" href="#form-inscricao">Tire aqui suas dúvidas e<br>faça sua pré-inscrição.</a></p>
            <h3>Pós-graduação em TTI<br><small>Terapias Transpessoais Integrativas</small></h3>
            <p class="lead">
                É um curso com as bases da Psicologia Transpessoal voltado para auto conhecimento porém com foco em Terapias Integrativas. Um curso realmente transformador, pois acreditamos que só podemos cuidar o outro quando cuidamos de nos!
            </p>
            <p>
                Um curso onde o aluno vai estudar a teoria e vivenciar muitas das terapias de acordo com  a PORTARIA No- 849, DE 27 DE MARÇO DE 2017, que define a inclusão de praticas Integrativas e Complementares no SUS.
            </p>
            <p>
                As aulas serão ministradas uma vez por mês, através de seminãrios com inicio na sexta feira das 19:00 as 22:30 e no sábado das 8:30 as 20:00 exceto os seminários de imersão que serão sábados e domingos.
            </p>
            <br>
            <!--<hr class="mb80">-->
            <h3>Objetivo Geral</h3>
            <p class="lead">
                <?=$this->objetivoGeral[0]?>
            </p>
            <ul>
                <?php foreach ($this->objetivoGeral[1] as $o): ?>
                    <li><?=$o?></li>
                <?php endforeach;?>
            </ul>
            <br>

            <?=$this->partial("formacao/tti-btn.phtml", $this)?>
            <br>
            <h3>Objetivos Específicos</h3>
            <p>
                <?=$this->objetivosEspecificos[0]?>
            </p>
            <ul>
                <?php foreach ($this->objetivosEspecificos as $o): ?>
                    <li><?=$o?></li>
                <?php endforeach;?>
            </ul>
            <!-- <br><br>
            <h3>Condições de pagamento</h3>
            <p>
                Matriculas realizadas até 30/03/2021 ficam em 250 reais.<br>
                Matrículas realizadas após 30/03/2021 ficam em 300 reais.
            </p>
            <p>
                A mensalidade são 24 parcelas de 554,00 reais. Mas caso o valor seja pago em dia, até o dia 10 de cada mês, será oferecido um desconto de 10% custando apenas 498,60 reais.
            </p>
            <h4>Dados para depósito</h4>
            <p class="lead">Garanta sua vaga depositando o valor da matrícula em nossa conta da VIACRED:</p>
            <p class="alert alert-primary" style="font-family: monospace;">
                ESPAÇO ANICHA LTDA. ME<br>
                <b>CNPJ:</b> 22.771.858/0001-92<br>
                <b>Banco:</b> 085 (VIACREDI – Blumenau/SC)<br>
                <b>Agência:</b> 101 (R. Gen. Osório, 3269 - Água Verde)<br>
                <b>Conta corrente:</b> 828.783-0<br>
            </p> -->
            <br>
            <!-- <h3>Início das aulas</h3>
            <p class="lead">16 de abril de 2021.</p> -->
            <p>
                Estamos muito felizes com a possibilidade de você participar desta turma!
            </p>
            <br><br>
            <h3 id="form-inscricao">Dúvidas?</h3>
            <?=$this->partial("itens/form.phtml", $this)?>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
        <div class="col-md-6">
            <p><a class="btn btn-sm btn-primary btn-block" href="/tti/turma2018">Clique aqui para ver o calendário<br>da turma anterior (2018-2020).</a></p>
            <h4>Caledário turma 2021-2023:</h4>
            <?php foreach ($this->modulos as $m): ?>
                <h3 style="color:<?=$m->cor?>"><?=$m->titulo?> <span class="label label-primary pull-right"><?=$m->getHoras()?> horas</span></h3>
                <table class="table table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th style="background:<?=$m->cor?>; border:none;">cód.</th>
                            <th style="background:<?=$m->cor?>; border:none;">tema</th>
                            <th style="background:<?=$m->cor?>; border:none;" class="text-center">professor</th>
                            <th style="background:<?=$m->cor?>; border:none;" class="text-center">carga horária</th>
                            <!-- <th style="background:<?=$m->cor?>; border:none;" class="text-center">data</th> -->
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($m->temas as $t): ?>
                            <tr>
                                <th><b><?=$t->codigo?></b></th>
                                <th><?=$t->nome?></th>
                                <th class="text-center"><?=$t->professor?></th>
                                <th class="text-center"><?=$t->horas?></th>
                                <!-- <th class="text-center">{{'<?=$t->data?>'|date}}</th> -->
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
                <br>
            <?php endforeach;?>
        </div>
    </div>
</div>