<section id="cotacaoSegurado" class="row">
    <div class="control-group col-sm-6" ng-repeat="p in pessoas">
        <button ng-click="cotacao.pessoa = p" type="button" class="btn btn-block {{p.id === cotacao.pessoa.id?'btn-warning active':'btn-black'}}"><i class="fa {{p.id === cotacao.pessoa.id?'fa-check-square-o':'fa-square-o'}}"></i> {{p.nome}}</button>
    </div>
    <div class="clearfix"></div>
    <br>
    <h3 class="col-sm-12" style="text-transform: none;">
        <span class="color1">Dados do segurado</span>
    </h3>
    <!-- EMPRESA -->
    <div class="control-group col-sm-6" ng-if="cotacao.pessoa.id === 2">
        <div class="form-group controls {{errors.cotacaoRazao?'has-error':''}}">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-industry"></i></span>
                <input name="name" type="text" ng-model="cotacao.razao" class="form-control" placeholder="Nome da Empresa">
            </div>
            <small class="helping-text" ng-if="errors.cotacaoRazao" style="color:white;"><i class="fa fa-warning"></i> {{errors.cotacaoRazao.message}}</small>
        </div>
    </div>
    <div class="control-group col-sm-6" ng-if="cotacao.pessoa.id === 2">
        <div class="form-group controls {{errors.cotacaoCnpj?'has-error':''}}">
            <div class="input-group">
                <span class="input-group-addon">CNPJ</span>
                <input name="name" type="text" ng-model="cotacao.cnpj" class="form-control" placeholder="99.999.999/9999-99">
            </div>
            <small class="helping-text" ng-if="errors.cotacaoCnpj" style="color:white;"><i class="fa fa-warning"></i> {{errors.cotacaoCnpj.message}}</small>
        </div>
    </div>
    <!-- /empresa -->
    <div class="control-group col-sm-12">
        <div class="form-group controls {{errors.cotacaoNome?'has-error':''}}">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                <input name="name" type="text" ng-model="cotacao.nome" class="form-control" placeholder="{{cotacao.pessoa.id === 1?'Nome do Segurado':'Nome do Responsável'}}">
            </div>
            <small class="helping-text" ng-if="errors.cotacaoNome" style="color:white;"><i class="fa fa-warning"></i> {{errors.cotacaoNome.message}}</small>
        </div>
    </div>
    <div class="control-group col-sm-6" ng-if="cotacao.pessoa.id === 1">
        <div class="form-group controls {{errors.cotacaoCpf?'has-error':''}}">
            <div class="input-group">
                <span class="input-group-addon">CPF</span>
                <input name="name" type="text" ng-model="cotacao.cpf" class="form-control" placeholder="999.999.999-99">
            </div>
            <small class="helping-text" ng-if="errors.cotacaoCpf" style="color:white;"><i class="fa fa-warning"></i> {{errors.cotacaoCpf.message}}</small>
        </div>
    </div>
    <div class="control-group col-sm-6">
        <div class="form-group controls {{errors.cotacaoTelefone?'has-error':''}}">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-phone"></i></span>
                <input name="telefone" type="text" ng-model="cotacao.telefone" class="form-control" placeholder="Celular para contato">
            </div>
            <small class="helping-text" ng-if="errors.cotacaoTelefone" style="color:white;"><i class="fa fa-warning"></i> {{errors.cotacaoTelefone.message}}</small>
        </div>
    </div>
    <div class="control-group col-sm-6" ng-if="cotacao.pessoa.id === 1">
        <div class="form-group controls {{errors.cotacaoCivil?'has-error':''}}">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-list"></i></span>
                <select name="civil" ng-model="cotacao.civil" class="form-control" ng-options="item for item in civis">
                    <option value="">Estado Civil:</option>
                </select>
            </div>
            <small class="helping-text" ng-if="errors.cotacaoCivil" style="color:white;"><i class="fa fa-warning"></i> {{errors.cotacaoCivil.message}}</small>
        </div>
    </div>
    <div class="control-group col-sm-6">
        <div class="form-group controls {{errors.cotacaoCep?'has-error':''}}">
            <div class="input-group">
                <span class="input-group-addon">CEP</span>
                <input name="cep" type="text" ng-model="cotacao.cep" class="form-control" placeholder="99999-999">
            </div>
            <small class="helping-text" ng-if="errors.cotacaoCep" style="color:white;"><i class="fa fa-warning"></i> {{errors.cotacaoCep.message}}</small>
        </div>
    </div>
    <div class="control-group col-sm-12" ng-if="cotacao.pessoa.id === 1">
        <div class="form-group controls {{errors.cotacaoNascimento?'has-error':''}}" style="margin-bottom: 0;">
            <div class="input-group">
                <span class="input-group-addon">Nascimento</span>
                <span class="input-group-addon" style="padding:0;">
                    <select name="nascDia" ng-model="cotacao.nascDia" class="form-control" ng-options="dia for dia in nascDias">
                        <option value="">dia</option>
                    </select>
                </span>
                <span class="input-group-addon" style="padding:0;">
                    <select name="nascMes" ng-model="cotacao.nascMes" class="form-control" ng-options="mes for mes in nascMeses">
                        <option value="">mês</option>
                    </select>
                </span>
                <span class="input-group-addon" style="padding:0;">
                    <select name="nascAna" ng-model="cotacao.nascAno" class="form-control" ng-options="ano for ano in nascAnos">
                        <option value="">ano</option>
                    </select>
                </span>
            </div>
        </div>
        <small class="helping-text" ng-if="errors.cotacaoNascimento" style="color:white;"><i class="fa fa-warning"></i> {{errors.cotacaoNascimento.message}}</small>
    </div>
</section>