<div class="career-box">
    <table>
        <tr>
            <td style="vertical-align: top; width: 33%">
                <a href="<?= $this->s->link ?>"><img src="<?= $this->s->foto ?>" alt="foto" class="img-responsive"></a>
                <div>
                    <a href="<?= $this->s->link ?>" class="btn btn-block btn-warning btn-sm"><i class="fa fa-pencil"></i>Ver mais</a>
                </div>
            </td>
            <td style="padding-left: 15px; width: 69%; vertical-align: top;">
                <h3 class="heading"><?= $this->s->nome ?></h3>
                <div class="info">
                    <p><?= $this->s->descricao ?></p>
                </div>
                <!--                                            <ul>
                                                                <li>Graduate (M. Phil.) </li>
                                                                <li>2+ Years Experience</li>
                                                            </ul>-->
                <!--<h6 class="heading">Qualification Required</h6>-->
            </td>
        </tr>
    </table>
</div>