<div class="col-sm-12">
    <div class="bloco-form bg-white">
        <form ef-post2="login" class="login" action="/user/pass/save" method="post">
            <h3 ng-init="login.user = <?= $this->userId ?>;
                    login.codigo = '<?= $this->codigo ?>';" style="font-weight: bold; text-shadow: 1px 1px 1px white; margin-top:0;">
                Escolha uma nova senha<br>
                <small style="color:black;">
                    Informe e repita sua nova senha:
                </small>
            </h3>
            <div class="form-group">
                <input ng-model="login.pass1" type="password" class="form-control input-lg" placeholder="Nova senha">
            </div>
            <div class="form-group">
                <input ng-model="login.pass2" type="password" class="form-control input-lg" placeholder="Repita sua nova senha">
            </div>
            <div ng-repeat="error in errors" ng-cloak="">
                <div class="alert alert-warning" ng-show="error.message">
                    <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
                    {{error.message}}
                </div>
            </div>
            <div class="form-group buttons">
                <span class="lead" ng-show="!loaded"><i class="fa fa-spinner fa-spin"></i> Aguarde...</span>
                <button type="submit" ng-show="loaded" class="btn btn-success btn-block btn-lg"><b>SALVAR NOVA SENHA</b></button>
            </div>
        </form>
    </div>
</div>