<div class="col-sm-12">
    <div class="bloco-form bg-white">
        <h3 style="font-weight: bold; text-shadow: 1px 1px 1px white; margin-top:0;">
            Uma mensagem foi enviada para <b><?= $this->email ?></b><br>
        </h3>
        <div style="font-weight: bold;">
            <p class="lead">O que fazer agora:</p>
            <ol class="text-left">
                <li>Entre no seu email (<?= $this->email ?>)</li>
                <li>Clique no link que enviamos</li>
                <li>Escolha uma nova senha</li>
            </ol>
        </div>
<!--        <div class="">
            <a href="/epanel" class="btn btn-default">Voltar</a>
        </div>-->
    </div>
</div>