<!-- About Section -->
<section class="success" id="about" style="background:#000;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Sobre nós</h2>
                <hr class="star-light">
                <br>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <p>A POA Vidros, mais nova tendência no comércio de vidros da capital gaúcha, conta com uma grande variedade de
                    serviços, desde manutenções até serviços decorativos, e o vasto e premiado currículo de seu proprietário.
                </p>
                <p>Ele, Jenivaldo, atua na área há mais de 20 anos, sempre inovando e buscando a perfeição em cada detalhe. Começou
                    trabalhando com seu sogro após sua chegada em Porto Alegre ­ em meados de 1990 ­ e, passado alguns meses
                    passou a liderar as equipes de trabalho de sua primeira empresa. E assim se passaram muitos anos, adquirindo
                    experiências, qualificando-se e buscando o melhor para oferecer aos seus clientes. Depois de uma breve passagem
                    por SC, retorna a Porto Alegre para continuar a sua caminhada ao lado dos vidros.
                </p>
                <p>Desde sua essência, a POA Vidros busca o seu diferencial: bom atendimento atrelado à agilidade.</p>
                <p>Essa busca por novidades, inovações e agilidade no atendimento permite que a POA Vidros inove e não conte com
                    uma loja física, apenas com um estoque, pois seus funcionários estão sempre prontos para o melhor atendimento, indo
                    ao encontro do seu cliente, aonde quer que ele esteja.
                </p>
                <p>Trabalhamos com nossos telefones, para um contato mais direto, e com a plataforma virtual, no site e por e­mail, para
                    um contato mais formal.
                </p>
                <p>Nossos clientes não são apenas mais um número, mas sim um novo amigo e um parceiro que nos ajuda a continuar a
                    escrita dessa carreira e história de sucesso.
                </p>
            </div>
            <div class="col-sm-6">
                <p><img src="/default/img/jenivaldo.jpg" alt="Jenivaldo" class="img-responsive"></p>
            </div>
        </div>
    </div>
</section>