<div style="height:7px; background: url(/img/top_shadow.png) bottom center no-repeat;"></div>
<table class="vertical top_box" style="width:800px;">
	<tr>
		<th></th><td><hr class="space" /></td>
	</tr>
	<tr>
		<th colspan="2" style="text-align:center">
			<hr class="space" />
			<h1>Sua senha foi alterada com sucesso!</h1>
			<h2><a href="/">Clique aqui para voltar à página inicial.</a></h2>
		</th>
	</tr>
</table>