<div style="height:7px; background: url(/img/top_shadow.png) bottom center no-repeat;"></div>
<table class="vertical top_box" style="width:800px;">
	<tr>
		<th></th><td><hr class="space" /></td>
	</tr>
	<tr>
		<th colspan="2" style="text-align:center">
			<hr class="space" />
			<h1>Uma mensagem foi enviada para <b><?=$this->email?></b>.</h1>
			<p>Entre no seu email e clique no link que enviamos, depois escolha uma nova senha.</p>
		</th>
	</tr>
</table>