<div id="rev_slider_1078_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="classic4export" data-source="gallery" style="margin:0px auto;background-color:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
    <!-- START REVOLUTION SLIDER 5.4.1 auto mode -->
    <div id="rev_slider_1078_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.4.1">
        <ul>
            <!-- SLIDE -->
            
            <!-- SLIDE  -->
            <li data-index="rs-3046" data-transition="parallaxtoleft" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off"  data-easein="Power4.easeInOut" data-easeout="Power4.easeInOut" data-masterspeed="2000" data-rotate="0"  data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off"  data-title="Intro" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="/template/images/bg7.jpg"  alt=""  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption mainSlide-Title   tp-resizeme"
                     id="slide-1706-layer-4"
                     data-x="['right','right','right','right']" data-hoffset="['50','50','50','20']"
                     data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','1']"
                     data-fontsize="['55','55','40','30']"
                     data-lineheight="['65','65','50','35']"
                     data-width="['1140','900','721','420']"
                     data-height="none"
                     data-whitespace="normal"

                     data-type="text"
                     data-responsive_offset="on"
                     data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]'
                     data-textAlign="['right','right','right','right']"
                     data-paddingtop="[0,0,0,0]"
                     data-paddingright="[0,0,0,0]"
                     data-paddingbottom="[10,10,10,10]"
                     data-paddingleft="[0,0,0,0]"

                     style="z-index: 6; white-space: normal;"><?=$this->chamadas["sala"]["lg-title"]?></div>
                <!-- LAYER NR. 3 -->
                <div class="tp-caption mainSlide-caption mainSlide-Subtitle  tp-resizeme"
                     id="slide-1706-layer-5"
                     data-x="['right','right','right','right']" data-hoffset="['50','50','50','20']"
                     data-y="['middle','middle','middle','middle']" data-voffset="['90','90','90','50']"
                     data-fontsize="['24','24','24','16']"
                     data-lineheight="['34','34','34','26']"
                     data-width="['800','700','621','420']"
                     data-height="none"
                     data-whitespace="normal"
                     data-type="text"
                     data-responsive_offset="on"
                     data-frames='[{"delay":1400,"speed":1500,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]'
                     data-textAlign="['right','right','right','right']"
                     data-paddingtop="[0,0,0,0]"
                     data-paddingright="[0,0,0,0]"
                     data-paddingbottom="[10,10,10,10]"
                     data-paddingleft="[0,0,0,0]"
                     style="z-index: 6; text-align:left; max-width:1170px; white-space: normal;"><?=$this->chamadas["sala"]["sm-title"]?></div>
            </li>

        </ul>
        <div class="tp-bannertimer" style="height: 7px; background-color: rgba(255, 255, 255, 0.25);"></div>	</div>
</div><!-- END REVOLUTION SLIDER -->