<div class="container mt-80 mb-60">
    <div class="row">
        <div class="col-sm-12">
            <div class="heading-block">
                <h2 class="heading">Blog <span class="color1">Madri</span> Seguros</h2>
                <p class="sub-heading">Fique por dentro do mundo dos seguros e conheça dicas importantes para fazer o melhor negócio</p>
            </div>
        </div>
        <?php foreach ($this->posts as $post) : ?>
            <div class="col-sm-4">
                <div class="blog-box">
                    <div class="blog-header">
                        <a href="/blog/post/id/<?= $post->id ?>/<?= $post->titulo_url ?>">
                            <img src="<?= $post->foto ?>" class="img-responsive" alt="">
                        </a>
                        <br/>
                        <h4 class="heading"><?= $post->titulo ?></h4>
                        <div class="blog-meta">
                            <ul class="meta-list">
                                <li class="posted-on"> 
                                    <a href="/blog/post/id/<?= $post->id ?>/<?= $post->titulo_url ?>">
                                        {{'<?= $post->data ?>'|date}}
                                    </a>
                                </li>
    <!--                                <li><a href=""><i class="fa fa-share-alt"></i></a></li>
                                <li><a href=""><i class="fa fa-heart"></i></a></li>
                                <li><a href=""><i class="fa fa-comment"></i></a></li>-->
                            </ul>
                        </div>                            
                    </div>
                    <br/>
                    <div class="blog-excerpt">
                        <p><?= $post->resumo ?>...</p>
                        <a href="/blog/post/id/<?= $post->id ?>/<?= $post->titulo_url ?>" class="btn btn-warning btn-sm">Ler mais</a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>