<!-- Slider Revolution -->
<div class="rev_slider_wrapper fullwidthbanner-container hidden-sm hidden-xs">
    <div id="slider" class="rev_slider fullwidthbanner" data-version="5.0.7">    
        <ul>	
            <!-- Slide 0 -->
            <li data-index="rs-120"
                data-transition="parallaxvertical"
                data-slotamount="default"  
                data-easein="default" 
                data-easeout="default" 
                data-masterspeed="default"  
                data-thumb=""  
                data-rotate="0"  
                data-fstransition="fade" 
                data-fsmasterspeed="1500" 
                data-fsslotamount="7" 
                data-saveperformance="off"  
                data-title="Cotação Rápida" 
                data-description="Madri Seguros">

                <!-- MAIN IMAGE -->
                <img src="/default/images/dummy.jpg" data-lazyload="/default/images/slider-10.jpg" alt=""  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>

                <!-- Small Text -->
                <div class="tp-caption tp-resizeme rs-parallaxlevel-0" 
                     id="layer-1-small-text" 
                     data-x="['left','left','left','left']" data-hoffset="['50','50','50','30']" 
                     data-y="['middle','middle','middle','middle']" data-voffset="['-120','-120','-120','-120']" 
                     data-width="none"
                     data-fontsize="['24', '24', '22', '16']"
                     data-height="28"
                     data-color="['#FFC741']"
                     data-whitespace="nowrap"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;" 
                     data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" 
                     data-mask_out="x:0;y:0;s:inherit;e:inherit;" 
                     data-start="1000" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-responsive_offset="on" 
                     style="z-index: 10; white-space: nowrap; font-weight:400;">Cotação Rápida <i class="fa fa-fighter-jet"></i>
                </div>

                <!-- Main Text -->
                <div class="tp-caption tp-resizeme rs-parallaxlevel-0" 
                     id="slide-1-main-text" 
                     data-x="['left','left','left','left']" data-hoffset="['50','50','50','30']" 
                     data-y="['middle','middle','middle','middle']" data-voffset="['-50','-50','-50','-50']" 
                     data-fontsize="['46','46','46','32']"
                     data-lineheight="['55','55','55','35']"
                     data-color="['#fff']"
                     data-width="['600','600','600','420']"
                     data-height="120"
                     data-whitespace="normal"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;" 
                     data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" 
                     data-mask_out="x:0;y:0;s:inherit;e:inherit;" 
                     data-start="1000" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-responsive_offset="on" 
                     style="z-index: 11; min-width: 600px; max-width: 600px; font-weight:400; white-space: normal; text-shadow:0px 2px 5px #000; text-align:left;">Madri Seguros
                </div>

                <!-- Button -->
                <a href="/seguros" class="tp-caption btn btn-warning rs-parallaxlevel-0 hidden-xs tp-resizeme" 
                   id="slide-1-button-1" 
                   data-x="['left','left','left','left']" data-hoffset="['53','53','53','30']" 
                   data-y="['middle','middle','middle','middle']" data-voffset="['0','50','50','50']" 
                   data-width="none"
                   data-height="none"
                   data-whitespace="nowrap"
                   data-transform_idle="o:1;"
                   data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" 
                   data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;" 
                   data-mask_in="x:0px;y:0px;" 
                   data-mask_out="x:0;y:0;" 
                   data-start="1000" 
                   data-splitin="none" 
                   data-splitout="none" 
                   data-responsive_offset="on" 
                   data-responsive="on"
                   style="z-index: 12;">FAZER COTAÇÃO
                </a>

                <!-- Button -->
                <!--                <a href="pricing-tables.html" class="tp-caption btn btn-black rs-parallaxlevel-0 hidden-xs tp-resizeme" 
                                   id="slide-1-button-2" 
                                   data-x="['left','left','left','left']" data-hoffset="['210','210','210','210']" 
                                   data-y="['middle','middle','middle','middle']" data-voffset="['50','50','50','50']" 
                                   data-width="none"
                                   data-height="none"
                                   data-whitespace="nowrap"
                                   data-transform_idle="o:1;"
                                   data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" 
                                   data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;" 
                                   data-mask_in="x:0px;y:0px;" 
                                   data-mask_out="x:0;y:0;" 
                                   data-start="1000" 
                                   data-splitin="none" 
                                   data-splitout="none" 
                                   data-responsive_offset="on" 
                                   data-responsive="on"
                                   style="z-index: 12;">Cotação Rápida
                                </a>-->
            </li>
            <!-- Slide 1 -->
            <li data-index="rs-129"
                data-transition="parallaxvertical"
                data-slotamount="default"  
                data-easein="default" 
                data-easeout="default" 
                data-masterspeed="default"  
                data-thumb=""  
                data-rotate="0"  
                data-fstransition="fade" 
                data-fsmasterspeed="1500" 
                data-fsslotamount="7" 
                data-saveperformance="off"  
                data-title="A STUDY ON HAPPINESS" 
                data-description="Nurturing the most awesome minds.">

                <!-- MAIN IMAGE -->
                <img src="/default/images/dummy.jpg" data-lazyload="/default/images/slider-4.jpg" alt=""  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>

                <!-- Small Text -->
                <div class="tp-caption tp-resizeme rs-parallaxlevel-0" 
                     id="layer-1-small-text" 
                     data-x="['left','left','left','left']" data-hoffset="['50','50','50','30']" 
                     data-y="['middle','middle','middle','middle']" data-voffset="['-120','-120','-120','-120']" 
                     data-width="none"
                     data-fontsize="['24', '24', '22', '16']"
                     data-height="28"
                     data-color="['#FCCF40']"
                     data-whitespace="nowrap"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;" 
                     data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" 
                     data-mask_out="x:0;y:0;s:inherit;e:inherit;" 
                     data-start="1000" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-responsive_offset="on" 
                     style="z-index: 10; white-space: nowrap; font-weight:400;">Um bom seguro...
                </div>

                <!-- Main Text -->
                <div class="tp-caption tp-resizeme rs-parallaxlevel-0" 
                     id="slide-1-main-text" 
                     data-x="['left','left','left','left']" data-hoffset="['50','50','50','30']" 
                     data-y="['middle','middle','middle','middle']" data-voffset="['-50','-50','-50','-50']" 
                     data-fontsize="['46','46','46','32']"
                     data-lineheight="['55','55','55','35']"
                     data-color="['#fff']"
                     data-width="['600','600','600','420']"
                     data-height="120"
                     data-whitespace="normal"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;" 
                     data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" 
                     data-mask_out="x:0;y:0;s:inherit;e:inherit;" 
                     data-start="1000" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-responsive_offset="on" 
                     style="z-index: 11; min-width: 600px; max-width: 600px; font-weight:400; white-space: normal; text-shadow:0px 2px 5px #000; text-align:left;">Começa com o<br>Corretor de Seguros.
                </div>

                <!-- Button -->
                <a href="/seguros" class="tp-caption btn btn-warning rs-parallaxlevel-0 hidden-xs tp-resizeme" 
                   id="slide-1-button-1" 
                   data-x="['left','left','left','left']" data-hoffset="['53','53','53','30']" 
                   data-y="['middle','middle','middle','middle']" data-voffset="['50','50','50','50']" 
                   data-width="none"
                   data-height="none"
                   data-whitespace="nowrap"
                   data-transform_idle="o:1;"
                   data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" 
                   data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;" 
                   data-mask_in="x:0px;y:0px;" 
                   data-mask_out="x:0;y:0;" 
                   data-start="1000" 
                   data-splitin="none" 
                   data-splitout="none" 
                   data-responsive_offset="on" 
                   data-responsive="on"
                   style="z-index: 12;">CONHEÇA NOSSOS PRODUTOS
                </a>

                <!-- Button -->
                <!--                <a href="pricing-tables.html" class="tp-caption btn btn-black rs-parallaxlevel-0 hidden-xs tp-resizeme" 
                                   id="slide-1-button-2" 
                                   data-x="['left','left','left','left']" data-hoffset="['210','210','210','210']" 
                                   data-y="['middle','middle','middle','middle']" data-voffset="['50','50','50','50']" 
                                   data-width="none"
                                   data-height="none"
                                   data-whitespace="nowrap"
                                   data-transform_idle="o:1;"
                                   data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" 
                                   data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;" 
                                   data-mask_in="x:0px;y:0px;" 
                                   data-mask_out="x:0;y:0;" 
                                   data-start="1000" 
                                   data-splitin="none" 
                                   data-splitout="none" 
                                   data-responsive_offset="on" 
                                   data-responsive="on"
                                   style="z-index: 12;">Cotação Rápida
                                </a>-->
            </li>

            <!-- Slide 2 -->
            <li data-index="rs-2"
                data-transition="parallaxvertical"
                data-slotamount="default"  
                data-easein="default" 
                data-easeout="default" 
                data-masterspeed="default"  
                data-thumb=""  
                data-rotate="0"  
                data-fstransition="fade" 
                data-fsmasterspeed="1500" 
                data-fsslotamount="7" 
                data-saveperformance="off"  
                data-title="Viagens" 
                data-description="Seguro Viagem Madri">

                <!-- MAIN IMAGE -->
                <img src="/default/images/dummy.jpg" data-lazyload="/default/images/slider-7.jpg" alt=""  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>

                <!-- Small Text -->
                <div class="tp-caption tp-resizeme rs-parallaxlevel-0" 
                     id="layer-1-small-text" 
                     data-x="['left','left','left','left']" data-hoffset="['50','50','50','30']" 
                     data-y="['middle','middle','middle','middle']" data-voffset="['-120','-120','-120','-120']" 
                     data-width="none"
                     data-fontsize="['24', '24', '22', '16']"
                     data-height="28"
                     data-color="['#CA9562']"
                     data-whitespace="nowrap"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;" 
                     data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" 
                     data-mask_out="x:0;y:0;s:inherit;e:inherit;" 
                     data-start="1000" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-responsive_offset="on" 
                     style="z-index: 10; white-space: nowrap; font-weight:400;">Rápido e confiável...
                </div>

                <!-- Main Text -->
                <div class="tp-caption tp-resizeme rs-parallaxlevel-0" 
                     id="slide-1-main-text" 
                     data-x="['left','left','left','left']" data-hoffset="['50','50','50','30']" 
                     data-y="['middle','middle','middle','middle']" data-voffset="['-50','-50','-50','-50']" 
                     data-fontsize="['46','46','46','32']"
                     data-lineheight="['55','55','55','35']"
                     data-color="['#fff']"
                     data-width="['600','600','600','420']"
                     data-height="120"
                     data-whitespace="normal"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" 
                     data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;" 
                     data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" 
                     data-mask_out="x:0;y:0;s:inherit;e:inherit;" 
                     data-start="1000" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-responsive_offset="on" 
                     style="z-index: 11; min-width: 600px; max-width: 600px; font-weight:400; white-space: normal; text-shadow:0px 2px 5px #000; text-align:left;">Seguro Viagem<br>Madri Seguros
                </div>

                <!-- Button -->
                <a href="/seguros/ver-mais/id/77" class="tp-caption btn btn-warning rs-parallaxlevel-0 hidden-xs tp-resizeme" 
                   id="slide-1-button-1" 
                   data-x="['left','left','left','left']" data-hoffset="['53','53','53','30']" 
                   data-y="['middle','middle','middle','middle']" data-voffset="['50','50','50','50']" 
                   data-width="none"
                   data-height="none"
                   data-whitespace="nowrap"
                   data-transform_idle="o:1;"
                   data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" 
                   data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;" 
                   data-mask_in="x:0px;y:0px;" 
                   data-mask_out="x:0;y:0;" 
                   data-start="1000" 
                   data-splitin="none" 
                   data-splitout="none" 
                   data-responsive_offset="on" 
                   data-responsive="on"
                   style="z-index: 12;">FAÇA AGORA O SEU
                </a>

                <!-- Button -->
                <!--                <a href="pricing-tables.html" class="tp-caption btn btn-black rs-parallaxlevel-0 hidden-xs tp-resizeme" 
                                   id="slide-1-button-2" 
                                   data-x="['left','left','left','left']" data-hoffset="['210','210','210','210']" 
                                   data-y="['middle','middle','middle','middle']" data-voffset="['50','50','50','50']" 
                                   data-width="none"
                                   data-height="none"
                                   data-whitespace="nowrap"
                                   data-transform_idle="o:1;"
                                   data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" 
                                   data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;" 
                                   data-mask_in="x:0px;y:0px;" 
                                   data-mask_out="x:0;y:0;" 
                                   data-start="1000" 
                                   data-splitin="none" 
                                   data-splitout="none" 
                                   data-responsive_offset="on" 
                                   data-responsive="on"
                                   style="z-index: 12;">Cotação Rápida
                                </a>-->
            </li>
        </ul>
    </div>
</div>
<!-- Revolution Slider Ends -->