<div id='diferenciais' class="bgcolor1 pt-60 pb-60" style="padding-top:20px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="iconbox-4">
                    <img src="/default/images/logowhite.png" alt="item" style="width: 40px;">
                    <br><br>
                    <h4 class="heading">Experiência</h4>
                    <p>Fundada em outubro de 2011 por diretores com mais de 10 anos de experiência no mercado de seguros atua hoje em 6 estados e nos mais variados ramos.</p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="iconbox-4">
                    <img src="/default/images/logowhite.png" alt="item" style="width: 40px;">
                    <br><br>
                    <h4 class="heading">Seguro Assertivo</h4>
                    <p>Conforme perfil e necessidade de cada cliente, assim garantindo um custo/benefício em favor do segurado. Madri tem o <span style="font-style: italic">know how</span> para atender da melhor forma possível.</p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="iconbox-4">
                    <img src="/default/images/logowhite.png" alt="item" style="width: 40px;">
                    <br><br>
                    <h4 class="heading">Atendimento</h4>
                    <p>Não se preocupe em ligar no 0800, o contato é direto com os profissinais da Madri Seguros, prontos para lhe atender 24 horas por dia nos 7 dias da semana. Acompanhamento diário em processos de sinistros.</p>
                </div>
            </div>
        </div>
    </div>
</div>