<div class="dzsparallaxer auto-init height-is-based-on-content "  data-options='{direction: "reverse"}'>
    <div class="divimage dzsparallaxer--target " style="width: 101%; height: 130%; background-image: url(/template/images/bg22.jpg)">
    </div>
    <div class="semi-black-overlay"></div>
    <div class="container pt100 pb100">
        <div class="row">
            <div class="col-md-8 mr-auto ml-auto">
                <h3 class="h1 text-center font300 text-white">ANICHA</h3>
            </div>
        </div>
    </div>
    <div class="dzsprxseparator--2triangles"></div>
</div><!--parallax-->
<div class="container pt90 pb60">
    <div class="row mb50">
        <div class="col-md-10 ml-auto mr-auto text-center">
            <h2 class="mb20 font300">Celebrando a impermanência...</h2>
            <p class="lead">
                Na língua hindi Anicha significa "impermanência". Anicha é aceitar e fluir com a vida e suas transformações sem resistir ou brigar com elas admitindo que a única certeza é a mudança.
            </p>
            <p>Nosso trabalho e missão consiste em levar até as pessoas maneiras poderosas de aproveitar cada presente que a vida nos dá através da promoção do auto-conhecimento e da cura profunda e transpessoal, para além dos limites do corpo. Por isso, organizamos um espaço capaz de abrigar as melhores técnicas e os melhores profissionais que conhecemos ao longo da nossa jornada. Venha conhecer! Você é o ingrediente principal e a razão da existência deste movimento.</p>
        </div>
    </div>
</div>
<div class="container-fluid" style="background:#F9F9F9">
    <div class="row">
        <div class="col-sm-12 col-md-6 no-padding">
            <img src="/template/images/bg24.jpg" alt="Anicha" style="width: 100%">
        </div>
        <div class="col-sm-12 col-md-6">
            <br>
            <br>
            <h2 class="mb20 font300">Espaço ANICHA</h2>
            <p class="lead">O Espaço Anicha está atendendo  em formato on-line, trazendo uma nova perspectiva de acolhimento e conforto através das inúmeras possibilidades deste fazer.</p>
            <p class="">Neste novo formato, você está livre para acompanhar no seu tempo e no conforto da sua casa todos os benefícios dos nossos cursos e atendimentos.</p>
            <p class="">Os atendimentos presenciais quando são realizados seguem todos os protocolos do ministério da saúde.</p>
            <p class="">Nossos profissionais continuam dando todo suporte e acolhimento a seus clientes</p>
            <!-- <p>Aproveite para colocar os pés no chão e ter acesso a atendimentos, como: 
                <?php
                $i = 1;
                $length = sizeof($this->menu->getByTipo(Menu::ATENDIMENTO)->itens);
                foreach ($this->menu->getByTipo(Menu::ATENDIMENTO)->itens as $a):
                    ?>
                    <a href="<?= $a->link ?>"><?= $a->nome ?></a><?= $i < $length ? ", " : "." ?>
                    <?php
                    $i++;
                endforeach;
                ?>
            </p> -->
            <!-- <p>
                Frequente periodicamente o Espaço Anicha através das nossas holopráxis: 
                <?php
                $i = 1;
                $length = sizeof($this->menu->getByTipo(Menu::HOLOPRAXIS)->itens);
                foreach ($this->menu->getByTipo(Menu::HOLOPRAXIS)->itens as $a):
                    ?>
                    <a href="<?= $a->link ?>"><?= $a->nome ?></a><?= $i < $length ? ", " : "." ?>
                    <?php
                    $i++;
                endforeach;
                ?>
            </p> -->
        </div>
    </div>
</div>

<div class="container pt90 pb60" style="margin-bottom: 0;">
    <div class="row mb50">
        <div class="col-md-10 ml-auto mr-auto text-center">
            <h2 class="mb20 font300">Nossos Fundadores</h2>
            <p class="lead">
                O Anicha foi criado pelo casal de biólogos <b>Jörg Henri Saar</b> e <b>Nilma de Jesus Furtado da Silva Saar</b>. Ambos compartilham uma grande experiência como donos de negócios que paralelamente às suas atividades empresariais trilharam um caminho de autoconhecimento e amadurecimento espiritual.
            </p>
            <p>É através do Espaço Anicha que hoje Jorg, Nilma e seus parceiros procuram entregar o que têm de melhor para o desenvolvimento humano integral capaz de impactar em melhores resultados na vida prática sem esquecer-se da Jornada Interior e o processo de autodescobrimento. Saiba um pouquinho mais sobre eles e nossa equipe...</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 text-center">
            <p><img src='/template/images/team-nilma.jpg' alt='Nilma' class="img-thumbnail" style='width: 100%'></p>
            <h4>Nilma de Jesus Furtado da Silva Saar</h4>
            <p>Bióloga; Terapeuta de Frequências de Brilho Nível 16 mais os níveis 29 a 46 com Pós-Graduação em Psicologia Transpessoal na UNIPAZ Sul; Formada em Terapias de Ampliação da Consciência pela UNIPAZ Sul. Professora Unipaz SC e terapeuta de polaridade sistêmica. Membro do Colégio Internacional dos Terapeutas CIT. Facilitadora de grupos femininos.</p>
        </div>
        <div class="col-md-6 text-center">
            <p><img src='/template/images/team-jorg.jpg' alt='Jorg' class="img-thumbnail" style='width: 100%'></p>
            <h4>Jörg Henri Saar</h4>
            <p>
                Biólogo; Terapeuta Amanae e Frequências de Brilho nível 3; Formado em Terapias de Ampliação da Consciência; Pós-Graduado em Psicologia Transpessoal na UNIPAZ Sul; “Professional Coach” pela Academia Brasileira de Coaching (ABRACOACHING); Professor no Programa de Psicologia Transpessoal da UNIPAZ Sul e do Curso de Parapsicologia do Instituto Namaskar em Joinville; Facilitador do movimento “Guerreiros do Coração” onde lidera grupos de homens; Dançarino e facilitador de grupos de Dança Circular Sagrada pela Triom sob a liderança de Renata Ramos.
            </p>
        </div>
    </div>
</div>

<!-- <div style="background: #F9F9F9">
    <div class="container pt90 pb60" style="margin-bottom: 0;">
        <div class="row mb50">
            <div class="col-md-10 ml-auto mr-auto text-center">
                <h2 class="mb20 font300">Parceiros e time de apoio</h2>
                <p class="lead">
                    Um sonho não se constrói sozinho. Nosso time também é composto dos melhores profissionais em suas respectivas áreas.
                </p>
            </div>
        </div>
        <div class="row">
            <?php foreach ($this->membros as $m) : ?>
                <div class="col-sm-12 col-md-6 col-lg-3 text-center">
                    <p><img src='/template/images/<?= $m[1] ?>' alt='Nilma' style='width: 100%; border-radius: 50%;'></p>
                    <h4><?= $m[0] ?></h4>
                    <p><?= $m[2] ?></p>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div> -->