<div class="blog-author">
    <div class="author-media">
        <img style="width:150px;" src="<?= $this->post->autor->foto ?>" class="author-img" alt="">
        <!--            <ul class="social">
                        <li><a href="#"><i class=" fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class=" fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class=" fa fa-pinterest-p"></i></a></li>
                        <li><a href="#"><i class=" fa fa-linkedin"></i></a></li>
                    </ul>-->
    </div>
    <div class="author-meta">
        <a href=""><h4 class="heading"><?= $this->post->autor->nome ?></h4></a>
        <!--<span class="author-desig">Senior Gynaecologist, MedWise Group</span>-->
        <p><?= $this->post->autor->descricao ?></p>
    </div>
</div>